done testcases
BigBullas/homework-1-autumn-2023 pull request #4
Opened 2023-10-02 13:48 UTC by qqq4u

2023-10-03 18:14 UTC, IvanStukalov requested changes

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
Все тесты в одном месте.
Разделить по функционалу "Стать автором", "Уведомления"

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
1 тест из "Тесты для авторизованного пользователя" и 1 тест из "Положительные тесты" повторяются

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
> +   открывается новая страница автора.
очень похожие тесткейсы
можно объединить

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
> +   открывается новая страница автора.
то же самое
можно объединить

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
> +   и выводится сообщение о том, что введённые данные некорректны.
из описания тесткейса можно подумать, что цифра - тоже невалидный символ (хотя судя по следующему тесткейсу - это не так)

2023-10-03 18:14 UTC, IvanStukalov commented on 4from5.md
> +6. При вводе **Описания блога**, содержащего символ отличный от кириллицы/латинницы(например, emoji), и нажатии кнопки "Стать автором",  выводится сообщение о том, что введённые данные некорректны.
снова вопрос к цифрам

2023-10-03 18:43 UTC, IvanStukalov requested changes

2023-10-03 18:43 UTC, IvanStukalov commented on 4from5.md
>  * [↓](#) Создание/редактирование/удаление поста
еще бы ссылки сделать на пункты, а то когда будем сливать, ничего не будет понятно

2023-10-04 08:46 UTC, qqq4u commented on 4from5.md
Убрал

2023-10-04 08:46 UTC, qqq4u commented on 4from5.md
Разделил, получилось 3 вообще

2023-10-04 08:46 UTC, qqq4u commented on 4from5.md
> +   открывается новая страница автора.
Похожие, но не одинаковые. Аттомарные и независящие, поэтому оставляю

2023-10-04 08:46 UTC, qqq4u commented on 4from5.md
> +   открывается новая страница автора.
Аналогично верхнему

2023-10-04 09:07 UTC, qqq4u commented on 4from5.md
> +6. При вводе **Описания блога**, содержащего символ отличный от кириллицы/латинницы(например, emoji), и нажатии кнопки "Стать автором",  выводится сообщение о том, что введённые данные некорректны.
Поправил

2023-10-04 09:07 UTC, qqq4u commented on 4from5.md
> +   и выводится сообщение о том, что введённые данные некорректны.
Поправил

2023-10-04 09:07 UTC, qqq4u commented on 4from5.md
>  * [↓](#) Создание/редактирование/удаление поста
Сделал ссылки

2023-10-05 07:35 UTC, IvanStukalov requested changes

2023-10-05 07:35 UTC, IvanStukalov commented on 4from5.md
> +2. При нажатии кнопки "Стать автором" в соответвующем модальном окне открывается страница созданного автора
не понимаю, в чем смысл делать отдельный раздел тестов
это же тоже тесты с нормальным ожидаемым поведением 
предлагаю внести эти тесты в раздел "Положительные тесты"

2023-10-05 07:35 UTC, IvanStukalov commented on 4from5.md
> +1. При отслеживании автора пользователь получит уведомление о новом его посте.
так же

2023-10-05 07:35 UTC, IvanStukalov commented on 4from5.md
> +3. При нажатии кнопки "Престать отслеживать" на странице автора, данный автор пропадает из списка отслеживаемых в пункте меню "Подписки"
здесь просто все тесты будут положительные

2023-10-05 22:53 UTC, BigBullas approved these changes

2023-10-06 06:43 UTC, qqq4u commented on 4from5.md
> +2. При нажатии кнопки "Стать автором" в соответвующем модальном окне открывается страница созданного автора
Тоже сомневался по этому поводу, перенесу

2023-10-06 06:44 UTC, qqq4u commented on 4from5.md
> +1. При отслеживании автора пользователь получит уведомление о новом его посте.
тут резонно, а вот выше - пожалуй оставлю

2023-10-06 06:44 UTC, qqq4u commented on 4from5.md
> +3. При нажатии кнопки "Престать отслеживать" на странице автора, данный автор пропадает из списка отслеживаемых в пункте меню "Подписки"
лучше так оставлю

2023-10-06 06:46 UTC, IvanStukalov approved these changes

2023-10-06 06:47 UTC, merged