added tests for finding authors, statistics and authors pages
BigBullas/homework-1-autumn-2023 pull request #6
Opened 2023-10-03 20:40 UTC by BigBullas

2023-10-04 13:57 UTC, qqq4u commented on 4from5.md
> +2. При вводе в input поле "Поиск авторов" полностью названия блога корректно отображается только искомый блог.
перефразируй, а то ощущение, что корректно отображается только искомый блог

2023-10-04 13:58 UTC, qqq4u commented on 4from5.md
> +4. При вводе в input поле "Поиск авторов" некорректный текст (к примеру, emoji) корректно отображается сообщение о том,
Не очень понятно, что такое некорректный текст

2023-10-04 14:10 UTC, qqq4u commented on 4from5.md
> +4. При убирании лайка с поста другим пользователем количество лайков в статистике корректно уменьшается на один.
Установка? УБирание?))

2023-10-04 14:11 UTC, qqq4u commented on 4from5.md
> +11. При выборе просмотра статистики за определённый период, если выбрать начальный месяц, который идёт раньше нынешнего, ничего
Наверное имеется в виду то, что выбрать нужно месяц, который идёт раньше месяца начала ведения автором блога, а не нынешнего. С нынешним всё должно меняться

2023-10-04 14:12 UTC, qqq4u commented on 4from5.md
> +12. При выборе просмотра статистики за определённый период, если выбрать начальный и конечный месяцы, которые оба идут
Там пустота? Или стата за последний месяц? А может нужно сказать юзеру о том, что выбраны плохие месяцы? Не очень понятно, что значит "ничего не изменится"

2023-10-05 08:41 UTC, IvanStukalov requested changes

2023-10-05 08:41 UTC, IvanStukalov commented on 4from5.md
> +1. При нажатии на карточку любого блога происходит переход именно на его страницу.
слово "именно" немного смущает. Как будто может быть по-другому

2023-10-05 08:41 UTC, IvanStukalov commented on 4from5.md
> +3. При вводе в input поле "Поиск авторов" общую часть нескольких названий блогов корректно отображаются только искомые блоги.
2 и 3 пункт лучше в один объединить
потому что если написать полностью название блога, например "мой блог", то может появиться он и блог с названием "мой блог про машины"
тогда получится, то 2 пункт неверен

2023-10-05 08:41 UTC, IvanStukalov commented on 4from5.md
> +1. При вводе в input поле "Поиск авторов" несуществующего названия блога корректно отображается сообщение о том,
что значит корректно?

2023-10-05 08:41 UTC, IvanStukalov commented on 4from5.md
> +1. При создании нового поста количество постов в статистике корректно увеличилось на один.
что значит корректно?

2023-10-06 06:42 UTC, BigBullas commented on 4from5.md
> +2. При вводе в input поле "Поиск авторов" полностью названия блога корректно отображается только искомый блог.
исправил

2023-10-06 06:42 UTC, BigBullas commented on 4from5.md
> +3. При вводе в input поле "Поиск авторов" общую часть нескольких названий блогов корректно отображаются только искомые блоги.
перефразировал 2 пункт

2023-10-06 06:45 UTC, BigBullas commented on 4from5.md
> +4. При вводе в input поле "Поиск авторов" некорректный текст (к примеру, emoji) корректно отображается сообщение о том,
пояснил

2023-10-06 06:47 UTC, BigBullas commented on 4from5.md
> +4. При убирании лайка с поста другим пользователем количество лайков в статистике корректно уменьшается на один.
изменил

2023-10-06 06:49 UTC, BigBullas commented on 4from5.md
> +11. При выборе просмотра статистики за определённый период, если выбрать начальный месяц, который идёт раньше нынешнего, ничего
верно, исправил

2023-10-06 06:53 UTC, BigBullas commented on 4from5.md
> +12. При выборе просмотра статистики за определённый период, если выбрать начальный и конечный месяцы, которые оба идут
Стата с начала ведения автором блога до нынешнего месяца, не пустота. Сообщать о том, что выбраны плохие месяцы необязательно

2023-10-06 06:56 UTC, IvanStukalov approved these changes

2023-10-06 06:56 UTC, qqq4u approved these changes

2023-10-06 07:00 UTC, merged