tests for authorization, settings and navigation
BigBullas/homework-1-autumn-2023 pull request #7
Opened 2023-10-04 05:20 UTC by DESOLATE17

2023-10-04 13:09 UTC, qqq4u commented on 4from5.md
> +3. При нажатии на иконку "глаза" инпут поле пароля показывается пользователю.
Инпут поле пароля всегда показывается пользователю)
Наверное имеется в виду его содержимое?

2023-10-04 13:15 UTC, qqq4u commented on 4from5.md
> +1. При нажатии на кнопку "Регистрация", открывается модальное окно для регистрации, но URL не меняется(баг).
А должен?
ПОчему баг сразу?

2023-10-04 13:19 UTC, qqq4u commented on 4from5.md
> +7. При нажатии на кнопку "Выйти", происходит редирект на главную страницу сервиса и выход из пользовательского аккаунта.
Шапка вверху так же меняется

2023-10-05 08:07 UTC, IvanStukalov requested changes

2023-10-05 08:07 UTC, IvanStukalov commented on 4from5.md
> +**Тесты для незарегистрированного пользователя**
может стоит разделить на положительные и отрицательные тесты?
или сделать " положительные и отрицательные тесты" подразделом

2023-10-05 08:07 UTC, IvanStukalov commented on 4from5.md
> +2. При нажатии на кнопку "Войти", открывается модальное окно для входа в аккаунт, но URL не меняется(баг).
не баг, потому что это попап

2023-10-05 08:07 UTC, IvanStukalov commented on 4from5.md
> +## Навигация по сервису и в меню настроек
мб еще стоит про переход по URL в адресной строке?

2023-10-05 08:20 UTC, DESOLATE17 commented on 4from5.md
> +**Тесты для незарегистрированного пользователя**
Здесь не подразумеваются отрицательные тесты, поэтому есть смысл делить только по типам пользователей

2023-10-05 08:32 UTC, DESOLATE17 commented on 4from5.md
> +1. При нажатии на кнопку "Регистрация", открывается модальное окно для регистрации, но URL не меняется(баг).
да, должна быть возможность скинуть другу ссылку на регистрацию на сервисе

2023-10-05 22:54 UTC, BigBullas approved these changes

2023-10-06 06:39 UTC, qqq4u approved these changes

2023-10-06 06:40 UTC, IvanStukalov approved these changes

2023-10-06 06:52 UTC, merged